services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env.development
    environment:
      - DOTENV_PUBLIC_KEY_DEVELOPMENT
    # The app runs on 8000 inside the container
    expose:
      - "8000"

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
